-- CampusConnect sample seed data (Cal Poly Pomona events)

BEGIN;

INSERT INTO events (
  title,
  description,
  category,
  date,
  end_date,
  location,
  venue,
  image_url,
  is_free,
  price,
  rsvp_count,
  capacity,
  source,
  source_url
)
VALUES
  (
    'Spring 2026 CS Career Prep Workshop',
    'Resume critiques, internship interview drills, and alumni mentoring for Computer Science majors.',
    'academic',
    '2026-03-05 14:00:00-08'::timestamptz,
    '2026-03-05 16:00:00-08'::timestamptz,
    'Building 3-2634 (CS dept)',
    'Computer Science Department Lab',
    'https://www.cpp.edu/events/images/spring-2026-cs-career-prep.jpg',
    true,
    0::numeric,
    22,
    80,
    'seed',
    'https://www.cpp.edu/events/seed/spring-2026-cs-career-prep-workshop'
  ),
  (
    'Bronco Startup Hack Night',
    'Student teams build startup prototypes and pitch to mentors from local tech companies.',
    'tech',
    '2026-04-10 18:00:00-07'::timestamptz,
    '2026-04-10 21:00:00-07'::timestamptz,
    'Building 3-2634 (CS dept)',
    'Innovation Lab 2634',
    'https://www.cpp.edu/events/images/bronco-startup-hack-night.jpg',
    true,
    0::numeric,
    36,
    120,
    'seed',
    'https://www.cpp.edu/events/seed/bronco-startup-hack-night-2026'
  ),
  (
    'BSC Club Rush and Community Mixer',
    'Meet student organizations, join interest groups, and connect with new classmates over games.',
    'social',
    '2026-02-19 11:30:00-08'::timestamptz,
    '2026-02-19 14:00:00-08'::timestamptz,
    'Bronco Student Center (BSC)',
    'Ursa Minor',
    'https://www.cpp.edu/events/images/bsc-club-rush-2026.jpg',
    true,
    0::numeric,
    40,
    200,
    'seed',
    'https://www.cpp.edu/events/seed/bsc-club-rush-community-mixer-2026'
  ),
  (
    'Rose Garden Sunset Jazz',
    'An outdoor evening set featuring CPP jazz ensemble standards and contemporary student arrangements.',
    'music',
    '2026-04-24 18:30:00-07'::timestamptz,
    '2026-04-24 20:00:00-07'::timestamptz,
    'Rose Garden',
    'Main Lawn Stage',
    'https://www.cpp.edu/events/images/rose-garden-sunset-jazz-2026.jpg',
    true,
    0::numeric,
    28,
    140,
    'seed',
    'https://www.cpp.edu/events/seed/rose-garden-sunset-jazz-2026'
  ),
  (
    'Bronco Intramural Soccer Kickoff',
    'Open scrimmages, team signups, and captain orientation for the spring intramural league.',
    'sports',
    '2026-03-28 09:00:00-07'::timestamptz,
    '2026-03-28 12:00:00-07'::timestamptz,
    'Quad Area',
    'South Field',
    'https://www.cpp.edu/events/images/bronco-intramural-soccer-kickoff-2026.jpg',
    true,
    0::numeric,
    31,
    120,
    'seed',
    'https://www.cpp.edu/events/seed/bronco-intramural-soccer-kickoff-2026'
  ),
  (
    'Taste of CPP Food Truck Friday',
    'Food trucks, student chef demos, and live DJ sets at the center of campus.',
    'food',
    '2026-05-01 12:00:00-07'::timestamptz,
    '2026-05-01 15:00:00-07'::timestamptz,
    'Bronco Student Center (BSC)',
    'BSC Plaza',
    'https://www.cpp.edu/events/images/taste-of-cpp-food-truck-friday-2026.jpg',
    false,
    8::numeric,
    34,
    180,
    'seed',
    'https://www.cpp.edu/events/seed/taste-of-cpp-food-truck-friday-2026'
  ),
  (
    'Fall Research Poster Symposium',
    'Undergraduate and graduate researchers present applied projects in engineering, science, and business.',
    'academic',
    '2026-09-23 13:00:00-07'::timestamptz,
    '2026-09-23 16:00:00-07'::timestamptz,
    'Kellogg West',
    'Conference Center Ballroom',
    'https://www.cpp.edu/events/images/fall-research-poster-symposium-2026.jpg',
    true,
    0::numeric,
    26,
    160,
    'seed',
    'https://www.cpp.edu/events/seed/fall-research-poster-symposium-2026'
  ),
  (
    'The Glass House Open Mic Night',
    'Students perform spoken word, indie sets, and acoustic covers in a relaxed evening showcase.',
    'social',
    '2026-10-08 19:00:00-07'::timestamptz,
    '2026-10-08 21:30:00-07'::timestamptz,
    'The Glass House (CLA)',
    'Glass House Stage',
    'https://www.cpp.edu/events/images/glass-house-open-mic-night-2026.jpg',
    true,
    0::numeric,
    18,
    90,
    'seed',
    'https://www.cpp.edu/events/seed/glass-house-open-mic-night-2026'
  ),
  (
    'CPP Cybersecurity Capture the Flag',
    'Hands-on red-team and blue-team security challenge hosted by the Cybersecurity Club.',
    'tech',
    '2026-11-14 10:00:00-08'::timestamptz,
    '2026-11-14 17:00:00-08'::timestamptz,
    'Building 3-2634 (CS dept)',
    'Cyber Lab',
    'https://www.cpp.edu/events/images/cpp-cybersecurity-ctf-2026.jpg',
    true,
    0::numeric,
    24,
    60,
    'seed',
    'https://www.cpp.edu/events/seed/cpp-cybersecurity-ctf-2026'
  ),
  (
    'Homecoming Quad Pep Rally',
    'Student performances, spirit squads, giveaways, and pre-game celebrations for Homecoming week.',
    'sports',
    '2026-10-30 16:00:00-07'::timestamptz,
    '2026-10-30 18:30:00-07'::timestamptz,
    'Quad Area',
    'Main Quad Stage',
    'https://www.cpp.edu/events/images/homecoming-quad-pep-rally-2026.jpg',
    true,
    0::numeric,
    37,
    200,
    'seed',
    'https://www.cpp.edu/events/seed/homecoming-quad-pep-rally-2026'
  );

COMMIT;
